server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessrecommandation
      database: fitnessrecommandation
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}
